### ISSUE TITLE
Refresh table meta data by SQL parse result

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1131]
### Which version of Sharding-Sphere do you using?

3.0.0.M3-SNAPSHOT

### Which project do you using? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC and Sharding-Proxy

### Expected behavior

For connection resource save reason, refresh table meta data should by SQL parse result.

### Actual behavior

Refresh table meta data load from database.

**Comment by codefairy08** [comment]
Write DDL grammar files, currently only write table index related statements   
- [ ] Develop grammar file MYSQL DDL g4 

- [ ] Develop grammar file Postgre DDL g4 

- [ ] Develop grammar file SQLServer DDL g4 

- [ ] Develop grammar file Oracle DDL g4 

Integrate the generated sql syntax parsing code into ss
- [ ] Integrate the generated mysql syntax  parsing code 

- [ ] Integrate the generated postgre syntax  parsing code 

- [ ] Integrate the generated sqlserver syntax  parsing code 

- [ ] Integrate the generated oracle syntax  parsing code
