### ISSUE TITLE
Sharding-Sphere 3.0.0 release plan

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1189]
sharding-sphere 3.0.0 plan to include 4 milestones.

- [x] 3.0.0.M1
  - [x] Rename from Sharding-JDBC to Sharding-Sphere #788
  - [x] Sharding-Proxy initial version
  - [x] SQL support for OR #501
  - [x] SQL support for batch insert of MySQL #290
  - [x] Support $->{..} for inline expression #702
  - [x] Support Spring Boot Starter 2.X #652
- [x] 3.0.0.M2
  - [x] Sharding-Proxy authorization #916
  - [x] Sharding-Proxy registry center #936
  - [x] SQL support for DCL #980
  - [x] support sharding metadata #758
- [x] 3.0.0.M3
  - [x] Sharding-Proxy support XA #902 
  - [x] Sharding-Orchestration API refactor #1153 #1201
  - [x] Sharding-JDBC spring namespace API refactor for master-slave #1203 
- [x] 3.0.0.M4
  - [x] Opentracing enhancement #1172 
  - [x] Support multiple database schema #1046
  - [x] Execute engine enhancement #1205 
  - [x] Adjust API of Hint usage #1289
  - [x] Refine package structure #1302
  - [x] Deprecated and remove sharding-jdbc-transaction-parent module #1305
  - [x] Refine maven module structure #1306
- [x] 3.0.0
  - [x] The enhancement for multiple schema #1301
  - [x] Adjust Orchestration API #1215 
  - [x] document
  - [x] example #1331 #1338
  - [x] release

**Comment by terrymanu** [comment]
Architecture of Sharding-Proxy:

![2018-08-27 12 00 12](https://user-images.githubusercontent.com/5516298/44639880-f441d380-a9f0-11e8-9b81-c7635660e801.png)

**Comment by joey168** [comment]
looking forward to the official version of 3.0.0

**Comment by olderzhou** [comment]
Let's hope this day coming soon

**Comment by fangdong116** [comment]
where is the maven repository url?

**Comment by terrymanu** [comment]
We use projects and milestone to manage issue, so close this issue.

**Comment by leader318** [comment]
sharding-sidecar  预计什么时候发布？

When will this software be released online?
