### ISSUE TITLE
Sharding-Sphere 3.1.0 release plan 

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1190]
- [ ] Sharding-JDBC support XA #1363 
- [ ] Sharding-Proxy support Local transaction #1238
- [ ] XA SPI for narayana #990
- [ ] Interaction with servicecomb-saga for BASE transaction #986
- [ ] Can parse hint on SQL parser engine  #1240
- [ ] Modify the API for RuleConfiguration #1410

**Comment by terrymanu** [comment]
We use projects and milestone to manage issue, so close this issue.
