### ISSUE TITLE
Sharding-Sphere 3.0.1 release plan

### ISSUE THREAD

**Issue by terrymanu** [sharding-sphere/sharding-sphere#1314]
- [ ] Refresh table meta data by SQL parse result #1131
  - [ ] New TCL parse engine #1239 
  - [x] Mysql aurora version not supported #1373
  - [x] YAML configuration & orchestration persist adjustment #1375
  - [x] Avoid to persist datasource implementation YAML in registry center #1395
  - [x] Sharding-Proxy master-slave mode Exception（Springboot+mybatis） #1403 
  - [ ] broadcast table support #1412

**Comment by terrymanu** [comment]
We use projects and milestone to manage issue, so close this issue.
